### ISSUE TITLE
Low Video Quality

### ISSUE THREAD

**Issue by t3rmin83r** [warnyul/fast-video-view#4]
I compared this video player with native VideoView. The video is pixelated and of poor quality. How can I improve the picture quality?

**Comment by warnyul** [comment]
Can you attach the video?

**Comment by t3rmin83r** [comment]
My app is running on an android device (not a phone or tablet) which is connected to some TV via HDMI cable. Here is a sample video:
http://player.vimeo.com/external/135279970.sd.mp4?s=65b9ce88f2862fb1d0ab995809da63a5&profile_id=112&oauth2_token_id=2579535

**Comment by warnyul** [comment]
I can't test on android TV, but I check video on mobile. I did not find differences between native and FastVideoView quality.
Is the video pixelated in native VideoView too on android TV?

**Comment by warnyul** [comment]
Can I close this issue @t3rmin83r?

**Comment by khawarraza** [comment]
Yes, please close this issue.
