### ISSUE TITLE
Crash on Android API 24+ 

### ISSUE THREAD

**Issue by DevilGeek** [warnyul/fast-video-view#6]
It will not work for android API  24+

```
 java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
        at android.view.TextureView.setBackgroundDrawable(TextureView.java:316)
        at android.view.View.setBackground(View.java:18263)
```

**Comment by warnyul** [comment]
The library do not call anywhere the setBackgroundDrawable method. So, can you give me more information about the issue?

**Comment by Houam-DEV** [comment]
Hey,

I'm working with @DevilGeek, we solved the issue.

We had `android:background="@android:color/transparent` and it no longer works on api 24+
